name: Docker Image Angular CI/CD
on:
  push:
    branches: [main]
env:
  IMAGE_NAME_VUE: ${{ secrets.DOCKER_REPOSITORY_VUE }}
  IMAGE_NAME_VUE_TAG: ${{ secrets.DOCKER_REPOSITORY_VUE }}:v${{ github.run_id }}.${{ github.run_number }}
 
jobs:
  build-vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Vue
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Vue Restore
        run: yarn --cwd ./SwiftCode.BBS.UI
      - name: Vue Build
        run: yarn --cwd ./SwiftCode.BBS.UI run build --prod
      - name: Docker Vue Image
        run: ls
      - name: Copy DockerFile
        run: cp ./SwiftCode.BBS.UI/Dockerfile ./SwiftCode.BBS.UI/dist
      - name: Copy Nginx
        run: cp -rf ./SwiftCode.BBS.UI/_nginx ./SwiftCode.BBS.UI/dist
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.us-west-1.aliyuncs.com
      - name: Build Image
        run: docker build -t ${{ env.IMAGE_NAME_VUE_TAG }} ./SwiftCode.BBS.UI/dist
      - name: Push Image
        run: docker push ${{ env.IMAGE_NAME_VUE_TAG }}

  pull-docker:
    needs: [build-vue]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            docker stop $(docker ps -a | grep ${{ env.IMAGE_NAME_VUE }} |  awk '{print $1}')
            docker rm -f $(docker ps -a | grep ${{ env.IMAGE_NAME_VUE }} |  awk '{print $1}')
            docker rmi -f $(docker images | grep ${{ env.IMAGE_NAME_VUE }} | awk '{print $3}')
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
            docker pull ${{ env.IMAGE_NAME_VUE_TAG }}
            docker run -d -p 8001:80  ${{ env.IMAGE_NAME_VUE_TAG }}
